package com.zing.doctor.module.sofa.task;

import com.zing.doctor.module.sofa.service.SofaService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.util.Map;

/**
 * SOFA 自动初评定时任务。
 *
 * <p>调度策略与 APACHE II 完全一致（{@code Apache2AutoScoreTask}）：
 * <ul>
 *   <li>执行周期：每天 01:00 一次（cron {@code 0 0 1 * * ?}）。
 *       2026-09-15 前为每 6 小时一次（01/07/13/19），因改为「终身一条」后
 *       其余 3 次只承担补跑作用、性价比低，按产品要求降为每日一次；</li>
 *   <li>入科阈值：{@code sofa.auto-generate.over-hours}，默认 24 小时，≤0 回退 24；</li>
 *   <li>扫描对象：与 APACHE II 共用同一条 SQL {@code IcuPatientMapper#selectInDepartPatientsOverHours}
 *       ——在科（is_in_depart=1、status=1、del_flag=0）且入科已超过阈值小时数；</li>
 *   <li>单次失败仅记录日志，不影响下一次调度。</li>
 * </ul>
 *
 * <p>为 {@code 在科且入科超过阈值小时数} 的患者生成 SOFA 初评（score_type=daily），
 * 取数范围为「评估时点前 24h（不足 24h 从入科时间起算）」。
 *
 * <p>幂等与并发：
 * <ul>
 *   <li>幂等：<b>已有任何评分记录</b>的患者直接跳过，重复执行/手动补跑都安全。
 *       2026-09-15 起按产品要求与 APACHE II 对齐：入科满 24h 后<b>终身只生成一条</b>自动记录。</li>
 *   <li>互斥：实际逻辑在 {@code SofaService#autoGenerateScores} 内以单实例锁串行化，
 *       避免与手动 {@code /api/sofa/auto-generate} 并发时“先查后插”重复建档。</li>
 * </ul>
 *
 * <p>可通过配置关闭：{@code sofa.auto-generate.enabled=false}；变更执行时间：
 * {@code sofa.auto-generate.cron}。
 */
@Slf4j
@Component
public class SofaAutoScoreTask {

    @Autowired
    private SofaService sofaService;

    /** 入科超过多少小时才生成初评，默认 24 小时 */
    @Value("${sofa.auto-generate.over-hours:24}")
    private int overHours;

    /** 是否启用每日自动初评，默认启用 */
    @Value("${sofa.auto-generate.enabled:true}")
    private boolean enabled;

    /**
     * 每天 01:00 生成 SOFA 初评（入科满 24h 且尚未评过的患者）。
     * <p>cron 为 6 段式（秒 分 时 日 月 周），默认 {@code 0 0 1 * * ?}。
     */
    @Scheduled(cron = "${sofa.auto-generate.cron:0 0 1 * * ?}")
    public void autoGenerateDaily() {
        if (!enabled) {
            log.info("[SOFA] 自动初评已关闭（sofa.auto-generate.enabled=false）");
            return;
        }
        long t0 = System.currentTimeMillis();
        try {
            Map<String, Object> r = sofaService.autoGenerateScores(null, overHours <= 0 ? 24 : overHours);
            log.info("[SOFA] 每日自动初评完成: 扫描={}, 建档={}, 跳过={}, 失败={}, 耗时={}ms",
                    r.get("scanned"), r.get("created"), r.get("skipped"), r.get("failed"),
                    System.currentTimeMillis() - t0);
        } catch (Exception e) {
            // 定时任务异常不抛出，避免影响调度线程后续触发
            log.error("[SOFA] 每日自动初评异常", e);
        }
    }
}
