package com.zing.doctor.module.sofa.task;

import com.zing.doctor.module.sofa.service.SofaService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.util.Map;

/**
 * SOFA 每日自动初评定时任务。
 *
 * <p>为「在科且入科超过 {@code sofa.auto-generate.over-hours} 小时、当日尚无评分记录」的患者
 * 生成一份 SOFA 初评（score_type=daily），取数范围为「当日 0 点（或入科时间）→ 现在」。
 *
 * <p>幂等与并发：
 * <ul>
 *   <li>幂等：当日已有评分记录的患者直接跳过，重复执行/手动补跑都安全；</li>
 *   <li>互斥：实际逻辑在 {@code SofaService#autoGenerateScores} 内以单实例锁串行化，
 *       避免与手动 {@code /api/sofa/auto-generate} 并发时“先查后插”重复建档。</li>
 * </ul>
 *
 * <p>可通过配置关闭：{@code sofa.auto-generate.enabled=false}；变更执行时间：
 * {@code sofa.auto-generate.cron}。
 */
@Slf4j
@Component
public class SofaAutoScoreTask {

    @Autowired
    private SofaService sofaService;

    /** 入科超过多少小时才生成初评，默认 24 小时 */
    @Value("${sofa.auto-generate.over-hours:24}")
    private int overHours;

    /** 是否启用每日自动初评，默认启用 */
    @Value("${sofa.auto-generate.enabled:true}")
    private boolean enabled;

    /**
     * 每天 02:30 生成当日 SOFA 初评。
     * <p>cron 为 6 段式（秒 分 时 日 月 周），默认 {@code 0 30 2 * * ?}。
     */
    @Scheduled(cron = "${sofa.auto-generate.cron:0 30 2 * * ?}")
    public void autoGenerateDaily() {
        if (!enabled) {
            log.info("[SOFA] 每日自动初评已关闭（sofa.auto-generate.enabled=false）");
            return;
        }
        long t0 = System.currentTimeMillis();
        try {
            Map<String, Object> r = sofaService.autoGenerateScores(null, overHours);
            log.info("[SOFA] 每日自动初评完成: 扫描={}, 建档={}, 跳过={}, 失败={}, 耗时={}ms",
                    r.get("scanned"), r.get("created"), r.get("skipped"), r.get("failed"),
                    System.currentTimeMillis() - t0);
        } catch (Exception e) {
            // 定时任务异常不抛出，避免影响调度线程后续触发
            log.error("[SOFA] 每日自动初评异常", e);
        }
    }
}
